### PR TITLE
Rebase against upstream/master (https://github.com/amkirwan/ember-oauth2)

### PR DESCRIPTION
**Pull request by catpham**
## Context
We're building a Campaign Monitor (CM) email capture app. (There is an analogous email capture app for MailChimp.)

As part of building out the CM email capture app, we need to implement an Oauth2 integration to allow customers to connect their CM account to their Intercom account. This is the preferred approach bc using API keys for authentication would make for a more cumbersome and less secure flow.  

In Embercom, we use [our own fork](https://github.com/intercom/ember-oauth2) of the [`ember-oauth2` library](https://github.com/amkirwan/ember-oauth2) to handle authentication with Mailchimp. We're trying to use the library also for authentication with CM and found a bug from a typo [here](https://github.com/intercom/ember-oauth2/blob/intercom/dist/ember-oauth2.js#L153):

```
if (this.get('scope')) uri += '&scope=' + encodeURIComponent(this.get('.scope')).replace('%20', '+');
```  

This bug was [fixed upstream](https://github.com/amkirwan/ember-oauth2/commit/75891f1abdb3c9a6d8fde87c80b76d462c0cf916), but remains in our fork. Scope is required for [CM Oauth2 authentication](https://www.campaignmonitor.com/api/getting-started/#authenticating-with-oauth).

This PR just rebases our fork against `upstream/master`. 

## Plan for migrating to new, rebased version of the library

- [ ] Ship [Embercom PR](https://github.com/intercom/embercom/pull/24859) to point to rebased branch:
```
"ember-oauth2": "intercom/ember-oauth2#jp/rebase-upstream-intercom",
```

- [ ] Merge `intercom/ember-oauth2` PR with [rebased branch](https://github.com/intercom/ember-oauth2/pull/1)

- [ ] Ship Embercom PR to point back to library main branch:
```
"ember-oauth2": "intercom/ember-oauth2#intercom",
```

## Open questions/items

1. Maybe we should use versions to manage the ember library?

2. See if we can get our changes merged back upstream so we don't have maintain the fork (https://github.com/amkirwan/ember-oauth2/pull/34)

### CODE REVIEW

**Comment by irvinebroque** [comment]
cc @intercom/team-dev-platform for 👀 - I think we use this library for a few other integrations?

**Comment by andremalan** [comment]
Merging our fix upstream and using theirs would be the better option for sure!  Maybe we can just nuke this repo entirely.

**Comment by mmartinic** [comment]
I don't think we use it for any integrations. We use omniauth in couple of places

**Review by irvinebroque — APPROVED** [review]

**Comment by catpham** [comment]
Created a different branch where I merged upstream changes instead of rebasing them. Makes for a cleaner history 😬: https://github.com/intercom/ember-oauth2/pull/2

**Pull request closed without merging**
